cabal-version:      3.0
name:               blog
version:            0.1.0.0
license:            GPL-3.0-only
license-file:       LICENSE
author:             Isaac Elliott
maintainer:         isaace71295@gmail.com
category:           Web
build-type:         Simple

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Blog
        Blog.ID
    build-depends:
        base ^>=4.20.2.0,
        bytestring,
        containers,
        entropy,
        filepath,
        sage,
        text >=2.0,
        tomlin
    hs-source-dirs:   src
    default-language: Haskell2010

executable blog
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.20.2.0,
        blog,
        bytestring,
        crypton-connection,
        crypton-x509-store,
        diagnostica,
        diagnostica-sage,
        directory,
        exceptions,
        filepath,
        http-client,
        http-client-tls,
        http-types,
        optparse-applicative,
        process,
        sage,
        text,
        time,
        tomlin,
        tls

    hs-source-dirs:   cli
    default-language: Haskell2010
    ghc-options:      -threaded

executable blog-server
    import:           warnings
    main-is:          Main.hs
    other-modules:
        Blog.Build
        Blog.Diagnostic
        Blog.Error
        Blog.Metadata
        Blog.Rules
        Blog.Store
        IO

        -- Vendored
        Commonmark.Pandoc
        Text.Pandoc.Builder
        Text.Pandoc.Definition
        Text.Pandoc.Html
        Text.Pandoc.Walk
    build-depends:
        base ^>=4.20.2.0,
        blog,
        bytestring,
        commonmark,
        commonmark-extensions,
        containers,
        deepseq,
        diagnostica,
        diagnostica-sage,
        directory,
        exceptions,
        filepath,
        http-types,
        mtl >=2.3.2,
        optparse-applicative,
        sage,
        syb,
        temple,
        text >=2.0,
        time,
        tomlin,
        transformers,
        wai,
        warp,
        warp-tls

    hs-source-dirs:   server
    default-language: Haskell2010
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N

test-suite blog-server-tests
    import:           warnings
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        async,
        base,
        barbies,
        blog,
        bytestring,
        containers,
        crypton-connection,
        crypton-x509-store,
        deepseq,
        directory,
        filepath,
        hedgehog,
        hspec,
        hspec-core,
        hspec-hedgehog,
        http-client,
        http-client-tls,
        http-types,
        mmorph,
        mtl,
        process,
        temporary,
        tls

    default-language: Haskell2010
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
